### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by Angristan** [m4ll0k/WPSeku#20] opened 2017-09-03 11:23 UTC
I'm using Arch Linux.

```
angristan@xps ~> cd WPSeku/
angristan@xps ~/WPSeku> pip install -r requirements.txt
Requirement already satisfied: requests in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests->-r requirements.txt (line 1))
Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib/python3.6/site-packages (from requests->-r requirements.txt (line 1))
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests->-r requirements.txt (line 1))
angristan@xps ~/WPSeku> chmod +x wpseku.py 
angristan@xps ~/WPSeku> ./wpseku.py 
  File "./wpseku.py", line 63
    print self.r+r"__        ______  ____       _          "+self.e
             ^
SyntaxError: Missing parentheses in call to 'print'
angristan@xps ~/WPSeku> python wpseku.py 
  File "wpseku.py", line 63
    print self.r+r"__        ______  ____       _          "+self.e
             ^
SyntaxError: Missing parentheses in call to 'print'
angristan@xps ~/WPSeku> python2 wpseku.py 
Traceback (most recent call last):
  File "wpseku.py", line 32, in <module>
    from modules.discovery import wpall
  File "/home/angristan/WPSeku/modules/discovery/wpall.py", line 24, in <module>
    from generic import wpgeneric 
  File "/home/angristan/WPSeku/modules/discovery/generic/wpgeneric.py", line 31, in <module>
    import wpversion 
  File "/home/angristan/WPSeku/modules/discovery/generic/wpversion.py", line 26, in <module>
    import requests
ImportError: No module named requests
angristan@xps ~/WPSeku> python3 wpseku.py 
  File "wpseku.py", line 63
    print self.r+r"__        ______  ____       _          "+self.e
             ^
SyntaxError: Missing parentheses in call to 'print'
angristan@xps ~/WPSeku> 
```

**Comment by m4ll0k** [comment] 2017-09-05 06:46
`chmod 777 wpseku.py`

**Comment by Angristan** [comment] 2017-09-05 09:22
Same issue, and I already made `wpseku.py` readable and executable.

**Comment by xanthuiop** [comment] 2017-11-19 11:04
it not work after `chmod`, and I also use archlinux

**Comment by 0xcrypto** [comment] 2017-12-19 04:49
You are probably using Python3. The script is written in Python2.x

**Comment by Angristan** [comment] 2017-12-19 19:04
@0xcrypto take a look a my message

**Comment by ubaidsworld** [comment] 2017-12-20 04:35
Hi @Angristan  after taking a look at your issue... I got it. See the version of python you are using isPython 3.6. The repository is compatible with the version 2.7.
In Python 3.6, `print `statement must be enclosed in parenthesis (). For example: print("Hello World!")
In Python 2.7, `print` statement does not need parenthesis and you can print the statement like: print "Hello World".
Hence, I suggest, use either Python 2.7 to run the program or if you want to use Python 3.6 only then make the program compatible. You can use the utility tool `2to3.py` which is available with the python3 versions.
I hope this will help you.

**Comment by 0xcrypto** [comment] 2017-12-20 06:27
@Angristan as @ubaidsworld said, you are indeed using python3 but script is written for python2.x But changing the whole script to python 3 (unless maintainers port it) is not a good option.

#22 explicitly calls python2 which ensures that you are using python2.x If you don't have python2 in your path, it will result in python2 command not found which tells that you need to use python2.x Since the commit is not yet merged, you can use my [fork](https://github.com/0xcrypto/WPSeku) until maintainers merge it or implements a patch.

**Comment by ubaidsworld** [comment] 2017-12-20 07:37
@0xcrypto See you might be right. But if the issue is with the print statements then @Angristan  can try fixing it. If not then Python 2.7 is always better to use.

**Closed** 2018-01-01 19:07 UTC
